Repository pluralsh/plural-cli, pull requests merged in 2022-06, with the labels that each got.

#101 Add crypto ssh-keygen command
  cmd/plural/crypto.go
  cmd/plural/validation.go
  pkg/bundle/configuration.go
  pkg/scm/github.go
  pkg/scm/gitlab.go
  pkg/scm/keys.go
  pkg/scm/provider.go
Labels: enhancement

#102 Demo Project Detection in CLI
  cmd/plural/bundle.go
  cmd/plural/repos.go
  pkg/api/recipes.go
  pkg/server/setup.go
  pkg/server/types.go
  tmux/.tmux.conf.local
Labels: enhancement

#98 upgrade to aws-sdk-go-v2
  go.mod
  go.sum
  pkg/provider/aws.go
Labels: enhancement, bug-fix

#106 Autodetect awscli version outdated
  cmd/plural/workspace.go
  pkg/api/recipes.go
Labels: bug-fix

#104 AWS: don't set bucket constraint for us-east-1
  pkg/provider/aws.go
Labels: bug-fix
