Repository pluralsh/plural-cli, pull requests merged in 2022-05, with the labels that each got.

#83 Add Labels to PR Template and improve checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#85 Auto-Infer Git User in Cloud Shell
  pkg/server/setup.go
  pkg/server/types.go
Labels: enhancement

#88 Add ability to list repos in csv format
  cmd/plural/repos.go
  pkg/format/csv.go
  pkg/format/formatter.go
  pkg/format/table.go
Labels: enhancement

#84 Add release notes template for automatic release generation.
  .github/release.yml
Labels: documentation

#87 Provider Preflight Checks
  cmd/plural/init.go
  cmd/plural/plural.go
  go.mod
  go.sum
  pkg/provider/aws.go
  pkg/provider/azure.go
  pkg/provider/equinix.go
  pkg/provider/gcp.go
  pkg/provider/kind.go
  pkg/provider/provider.go
  pkg/server/setup.go
  pkg/server/types.go
Labels: enhancement

#91 Inject commit and version into goreleaser builds
  .goreleaser.yaml
Labels: bug-fix

#95 Don't reuse previous deploy keys
  pkg/scm/keys.go
Labels: bug-fix

#96 Bypass helm delete errors due to nonexistent release
  pkg/wkspace/actions.go
Labels: bug-fix

#97 Reorder `plural init` flow to prevent repo recreation
  cmd/plural/init.go
  pkg/manifest/manifest.go
  pkg/provider/aws.go
  pkg/provider/azure.go
  pkg/provider/equinix.go
  pkg/provider/gcp.go
  pkg/provider/kind.go
  pkg/provider/provider.go
Labels: enhancement

#99 Reduce scroll speed in cloud shell
  tmux/.tmux.conf.local
Labels: bug-fix
