Repository pluralsh/plural-cli, pull requests merged in 2022-12, with the labels that each got.

#287 [WIP] add lua template
  cmd/plural/push.go
  go.mod
  go.sum
  pkg/api/charts.go
  pkg/api/models.go
  pkg/scaffold/helm.go
  pkg/scaffold/template/gotpl.go
  pkg/scaffold/template/lua.go
  pkg/scaffold/template/lua_test.go
  pkg/scaffold/template/template.go
  pkg/template/template.go
  pkg/test/lua/values.yaml.lua
  pkg/utils/lua.go
Labels: enhancement

#288 Add ability to upload docs folders for repositories
  pkg/api/repos.go
  pkg/api/repos_test.go
  pkg/api/terraform.go
  pkg/pluralfile/attrs.go
Labels: enhancement

#290 improve error handling for gql
  cmd/plural/crypto.go
  cmd/plural/help.go
  cmd/plural/init.go
  pkg/crypto/backup.go
Labels: enhancement

#289 check if 'output' exists, other bug fixes
  cmd/plural/push.go
  pkg/scaffold/template/lua.go
  pkg/scaffold/template/lua_test.go
  pkg/scaffold/template/template.go
  pkg/test/lua/values.yaml.lua
  pkg/utils/lua.go
Labels: bug-fix

#291 Extend cli server context apis
  pkg/server/configuration.go
  pkg/server/configuration_test.go
  pkg/server/context.go
Labels: enhancement

#293 Make `--from` flag for `plural deploy` support lists
  cmd/plural/deploy.go
  cmd/plural/plural.go
  cmd/plural/plural_test.go
  pkg/wkspace/graph.go
Labels: enhancement

#297 Optimistically create kubeconfig in shell
  pkg/server/setup.go
Labels: bug, bug-fix

#296 delete azure node
  go.mod
  go.sum
  pkg/provider/azure.go
Labels: bug-fix

#295 improve azure storage account creation
  pkg/provider/azure.go
  pkg/provider/azure_utils_test.go
Labels: enhancement

#298 destroy --force improvements
  cmd/plural/deploy.go
Labels: enhancement

#294 fix crypto share
  pkg/api/users.go
  pkg/crypto/age.go
  pkg/crypto/age_test.go
Labels: bug-fix

#299 Add context globals to reconfigure shared components in a workspace
  pkg/manifest/context.go
  pkg/scaffold/helm.go
  pkg/server/context_test.go
Labels: enhancement

#300 Clean up vpn command setup
  cmd/plural/deploy.go
  cmd/plural/plural.go
  cmd/plural/validation.go
  cmd/plural/vpn.go
  cmd/plural/vpn_test.go
  pkg/scaffold/crd.go
Labels: enhancement
