Repository pluralsh/plural-cli, pull requests merged in 2023-04, with the labels that each got.

#381 Bump gqlclient
  go.mod
  go.sum
Labels: enhancement

#384 Implement retries when fetching eab creds
  go.mod
  go.sum
  pkg/template/funcs.go
Labels: enhancement

#385 Fix crypto unlock
  cmd/plural/crypto.go
Labels: bug-fix

#386 fix: add configuration for helm values linting
  pkg/scaffold/template/template.go
Labels: bug-fix

#383 Allow setting release status
  pkg/api/repos.go
Labels: enhancement

#390 Filter kind provider
  pkg/provider/provider.go
Labels: bug-fix

#391 feat: Implement `plural upgrade`
  cmd/plural/plural.go
  cmd/plural/upgrade.go
  go.mod
  go.sum
  pkg/api/client.go
  pkg/api/upgrades.go
  pkg/api/users.go
  pkg/test/mocks/Client.go
  pkg/test/mocks/Kube.go
Labels: enhancement

#392 feat: Add repository contributors updates
  go.mod
  go.sum
  pkg/api/repos.go
  pkg/api/repos_test.go
Labels: enhancement

#394 fix: deploy action
  .github/workflows/goreleaser-cd.yml
Labels: bug-fix, hotfix

#395 improve bounce helm
  pkg/wkspace/minimal.go
Labels: enhancement

#396 Add `plural clone` command
  Makefile
  cmd/plural/crypto.go
  cmd/plural/dependencies.go
  cmd/plural/dependencies_test.go
  cmd/plural/deploy.go
  cmd/plural/deploy_test.go
  cmd/plural/init.go
  cmd/plural/plural.go
Labels: enhancement

#397 fix: Add preflight checks and improve error handling in the UI
  Makefile
  cmd/plural/ui.go
  go.sum
  pkg/bundle/oidc.go
  pkg/ui/client.go
  pkg/ui/web/package.json
  pkg/ui/web/package.json.md5
  pkg/ui/web/src/Plural.tsx
  pkg/ui/web/src/grommet/fileInputTheme.tsx
  pkg/ui/web/src/grommet/theme.ts
  pkg/ui/web/src/routes/installer/ConfigurationFileInput.tsx
  pkg/ui/web/src/routes/installer/Installer.tsx
  pkg/ui/web/src/routes/root.tsx
  pkg/ui/web/src/services/apollo.tsx
  pkg/ui/web/src/services/wails.ts
  pkg/ui/web/src/styled/theme.ts
  pkg/ui/web/src/types/styled.d.ts
  pkg/ui/web/wailsjs/go/ui/Client.d.ts
  pkg/ui/web/wailsjs/go/ui/Client.js
  pkg/ui/web/yarn.lock
Labels: bug-fix

#398 feat: Cluster Ownership transfer
  cmd/plural/clusters.go
  cmd/plural/plural.go
  go.mod
  go.sum
  pkg/api/client.go
  pkg/api/cluster.go
  pkg/manifest/manifest.go
  pkg/test/mocks/Client.go
Labels: enhancement

#399 Show better error messages when no primary bundle is found
  cmd/plural/bundle.go
Labels: bug-fix
