Repository pluralsh/plural-cli, pull requests merged in 2024-10, with the labels that each got.

#554 Write stack service account file to right path
  pkg/up/generate.go
Labels: bug-fix, hotfix

#555 Fix nametemplate
  .goreleaser.yaml
Labels: bug-fix, hotfix

#553 chore: Backfill args usage on recent commands
  cmd/command/api/api.go
  cmd/command/api/api_test.go
  cmd/command/auth/auth.go
  cmd/command/bounce/bounce.go
  cmd/command/bundle/bundle.go
  cmd/command/cd/cd.go
  cmd/command/cd/cd_clusters.go
  cmd/command/cd/cd_contexts.go
  cmd/command/cd/cd_credentials.go
  cmd/command/cd/cd_notifications.go
  cmd/command/cd/cd_pipelines.go
  cmd/command/cd/cd_repositories.go
  cmd/command/cd/cd_services.go
  cmd/command/cd/cd_settings.go
  cmd/command/clone/clone.go
  cmd/command/config/config.go
  cmd/command/crypto/crypto.go
  cmd/command/deploy/deploy.go
  cmd/command/destroy/destroy.go
  cmd/command/info/info.go
  cmd/command/link/link.go
  cmd/command/log/logs.go
  cmd/command/log/logs_test.go
  cmd/command/ops/ops.go
  cmd/command/ops/ops_test.go
  cmd/command/output/output.go
  cmd/command/packages/packages.go
  cmd/command/pr/pr.go
  cmd/command/profile/profile.go
  cmd/command/proxy/proxy.go
  cmd/command/push/push.go
  cmd/command/repo/repos.go
  cmd/command/stack/stacks.go
  cmd/command/upgrade/upgrade.go
  cmd/command/vpn/vpn.go
  cmd/command/workspace/workspace.go
  go.mod
  go.sum
Labels: enhancement

#557 fix: update goreleaser.yaml
  .goreleaser.yaml
Labels: bug-fix

#556 fix plural version
  Makefile
Labels: bug-fix

#558 add plrlctl formula to homebrew-plural and revert to single job build and release
  .github/workflows/ci.yaml
  .github/workflows/goreleaser-cd.yml
  .goreleaser.yaml
  Makefile
Labels: enhancement

#559 change plrlctl formula
  .goreleaser.yaml
Labels: enhancement

#561 setup docker container driver
  .github/workflows/goreleaser-cd.yml
Labels: bug-fix

#562 Start using main branch from bootstrap
  pkg/up/generate.go
Labels: enhancement, hotfix

#564 Revert main plural-cli name template
  .goreleaser.yaml
Labels: bug-fix, hotfix

#565 Add validation arg to contracts command
  cmd/command/pr/pr.go
  pkg/utils/git/repo.go
Labels: enhancement

#566 better streamline plural up --cloud
  .github/workflows/ci.yaml
  cmd/command/cd/cd_clusters.go
  cmd/command/up/up.go
  dockerfiles/Dockerfile.cloud
  pkg/manifest/manifest.go
  pkg/provider/aws.go
  pkg/provider/azure.go
  pkg/provider/equinix.go
  pkg/provider/gcp.go
  pkg/provider/kind.go
  pkg/provider/linode.go
Labels: enhancement

#567 Remove cleanup phase from plural up
  pkg/up/generate.go
  pkg/up/prune.go
Labels: bug-fix, hotfix

#568 Fix cloud cluster autoselection
  cmd/command/cd/cd.go
  cmd/command/up/up.go
  pkg/client/plural.go
  pkg/common/common.go
  pkg/provider/aws.go
  pkg/provider/azure.go
  pkg/provider/gcp.go
  pkg/provider/linode.go
  pkg/provider/provider.go
Labels: bug-fix, hotfix

#570 add ENUM type input
  pkg/api/models.go
  pkg/bundle/configuration.go
  pkg/bundle/configuration_test.go
  pkg/bundle/surveys.go
  pkg/bundle/types.go
  pkg/pr/crd.go
  pkg/pr/crd_test.go
  test/prautomation/prautomations.yaml
Labels: enhancement
