Repository pluralsh/plural-cli, pull requests merged in 2024-11, with the labels that each got.

#572 bump console client
  go.mod
  go.sum
  hack/gen-client-mocks.sh
  pkg/console/console.go
  pkg/console/pipelines.go
  pkg/test/mocks/Client.go
  pkg/test/mocks/ConsoleClient.go
  pkg/test/mocks/Kube.go
Labels: dependencies

#573 feat: add yaml overlay setting to plural pr template
  go.mod
  go.sum
  pkg/pr/apply_test.go
  pkg/pr/crd.go
  pkg/pr/types.go
  pkg/pr/updates.go
Labels: enhancement

#575 Add template to pr automation regexes
  pkg/pr/updates.go
Labels: enhancement, hotfix

#576 fix vulnerabilities
  Dockerfile
  go.mod
  go.sum
Labels: dependencies
