Repository pluralsh/plural-cli, pull requests merged in 2024-03, with the labels that each got.

#499 Add ability to add custom values to agent installs
  cmd/plural/cd.go
  cmd/plural/cd_clusters.go
  go.mod
  go.sum
  pkg/console/agent.go
  pkg/utils/file.go
Labels: enhancement, hotfix

#500 Get Namespace before creating
  pkg/kubernetes/kube.go
Labels: bug-fix

#498 feat: add cd notification commands
  cmd/plural/cd.go
  cmd/plural/cd_notifications.go
  go.mod
  go.sum
  pkg/console/console.go
  pkg/console/notification.go
  pkg/test/mocks/ConsoleClient.go
Labels: enhancement
