Repository pluralsh/plural-cli, pull requests merged in 2024-06, with the labels that each got.

#514 Bump s3 dependencies
  go.mod
  go.sum
Labels: bug-fix, hotfix

#515 Fix goreleaser version
  .github/workflows/ci.yaml
  .github/workflows/goreleaser-cd.yml
Labels: bug-fix, hotfix

#516 Slight changes to `plural up` process
  cmd/plural/up.go
  pkg/up/context.go
  pkg/up/deploy.go
  pkg/up/generate.go
  pkg/up/template.go
  pkg/up/types.go
  pkg/utils/git/repo.go
Labels: enhancement

#518 feat: add 'plural cd stacks gen-backend' command
  .github/workflows/ci.yaml
  Makefile
  cmd/plural/cd.go
  cmd/plural/cd_providers.go
  cmd/plural/cd_stacks.go
  go.mod
  go.sum
  pkg/console/console.go
  pkg/console/stacks.go
  pkg/stacks/helpers.go
  pkg/stacks/templates.go
  pkg/stacks/templates/_override.tf.gotmpl
  pkg/test/mocks/Client.go
  pkg/test/mocks/ConsoleClient.go
  pkg/test/mocks/Kube.go
  pkg/up/generate.go
  pkg/utils/git/ignore.go
Labels: enhancement

#519 Need to use consoleToken when running gen-backend
  cmd/plural/cd_stacks.go
Labels: bug-fix, hotfix

#520 Test dns before ping
  go.mod
  go.sum
  pkg/up/deploy.go
  pkg/up/ping.go
Labels: enhancement, hotfix

#521 Proper generation of ext urls
  cmd/plural/cd_clusters.go
  go.mod
  go.sum
  pkg/console/clusters.go
  pkg/console/console.go
  pkg/test/mocks/ConsoleClient.go
Labels: enhancement

#523 Prune unneeded resources post `plural up`
  cmd/plural/up.go
  pkg/up/deploy.go
  pkg/up/generate.go
  pkg/up/prune.go
Labels: enhancement, hotfix
