Repository pluralsh/plural-cli, pull requests merged in 2024-05, with the labels that each got.

#507 fix namespace creation for deployment operator
  cmd/plural/bootstrap.go
  cmd/plural/cd.go
  pkg/kubernetes/kube.go
Labels: bug-fix

#508 Kevin/eng 2029 use agent version specified in deployment settings from cli
  cmd/plural/cd.go
  go.mod
  go.sum
  pkg/console/agent.go
Labels: bug-fix

#509 Add `plural cd services template`
  .github/workflows/add-asana-comment.yaml
  cmd/plural/cd_services.go
  go.mod
  go.sum
  pkg/cd/template/render.go
  pkg/cd/template/utils.go
Labels: enhancement, hotfix

#510 fix dependencies
  cmd/plural/bootstrap.go
  go.mod
  go.sum
  pkg/test/mocks/Client.go
  pkg/test/mocks/ConsoleClient.go
  pkg/test/mocks/Kube.go
  pkg/utils/backup/capi.go
Labels: bug-fix

#511 check if deployment operator already exists
  cmd/plural/cd.go
  pkg/console/agent.go
Labels: enhancement

#512 Fallback to reinstall in `cd clusters bootstrap` command
  cmd/plural/cd_clusters.go
  pkg/console/errors/like.go
Labels: enhancement
