Repository pluralsh/plural-cli, pull requests merged in 2025-06, with the labels that each got.

#635 fix(e2e): try to avoid dns caching for plural up retries
  test/plural/up.yml
Labels: bug-fix

#638 Add retries to key creation
  pkg/scm/github.go
Labels: enhancement

#637 AppDomain input from workspace.yaml
  pkg/manifest/types.go
  pkg/up/template.go
Labels: enhancement

#639 Ensure plural up can handle built-in o11y
  .github/workflows/goreleaser-cd.yml
  pkg/up/generate.go
Labels: enhancement, hotfix

#640 o11y improvements
  pkg/up/generate.go
Labels: enhancement

#643 Fix append support for utils.merge lua
  go.mod
  go.sum
  test/lua/fsmerge.lua
Labels: bug-fix, hotfix

#644 Add app domain input in plural up
  cmd/command/down/down.go
  cmd/command/up/up.go
  pkg/common/app.go
  pkg/up/deploy.go
  pkg/up/generate.go
Labels: enhancement

#645 chore: bump polly to v0.3.0
  go.mod
  go.sum
Labels: dependencies
