Repository pluralsh/plural-cli, pull requests merged in 2025-07, with the labels that each got.

#647 fix: Remove iam.serviceAccounts.getAccessToken preflight check
  pkg/provider/permissions/gcp.go
Labels: bug-fix

#646 fix(e2e): use sudo for DNS override commands in e2e setup and fix askAppDomain
  .github/workflows/e2e.yaml
  cmd/command/up/up.go
  test/plural/up.yml
Labels: bug-fix

#650 `plural up` commit msg fix
  cmd/command/up/up.go
Labels: enhancement, hotfix

#651 feat: Add DNS domain checks for AWS and Azure
  cmd/command/up/up.go
  go.mod
  go.sum
  pkg/provider/aws.go
  pkg/provider/azure.go
Labels: enhancement

#654 fix: Fix managed zones issues
  cmd/command/up/up.go
  pkg/provider/gcp.go
Labels: bug-fix

#653 feat: Add in original IAM session to AWS templating context
  go.mod
  go.sum
  pkg/provider/aws.go
  pkg/provider/aws_session_context.go
Labels: enhancement

#655 fix: AWS context
  pkg/provider/aws.go
Labels: bug-fix

#656 fix: Switch func that generates erlang secret
  pkg/cd/control_plane_install.go
  pkg/crypto/rand.go
Labels: bug-fix

#658 Apply creates before updates
  pkg/pr/apply.go
Labels: enhancement
